# Generated by Django 3.1 on 2020-10-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201003_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='companynote',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactnote',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='careers',
            field=models.URLField(blank=True, help_text='(A link to the company job board)', null=True),
        ),
    ]
