# Generated by Django 3.1 on 2020-10-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201005_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynote',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
