# Generated by Django 3.1 on 2020-10-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201018_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='twitter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
