# Generated by Django 3.1 on 2020-10-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201021_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companynote',
            options={'ordering': ['-pk']},
        ),
    ]
