# Generated by Django 3.1 on 2020-10-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201021_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companynote',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-pk']},
        ),
    ]
