# Generated by Django 3.1 on 2020-10-27 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201021_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='motivation',
            field=models.CharField(choices=[('UNDECIDED', 'Undecided'), ('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], default='UNDECIDED', max_length=9),
        ),
        migrations.AddField(
            model_name='conversation',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
