# Generated by Django 3.1 on 2020-10-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201027_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='date_time',
        ),
    ]
