# Generated by Django 3.1 on 2020-10-28 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201027_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
